### ISSUE TITLE
Find volunteer team to develop guide for non-project portfolio page

### ISSUE THREAD

**Issue by Barny-6** [CodeYourFuture/Barny#51]
Find a team to develop a guide of alternative ways to showcase your work which isn't easily demoed

**Background**
 (see [#33](https://github.com/CodeYourFuture/Barny/issues/33))

**Acceptance Criteria**
- [ ] Find a team of at least 2 volunteers who agree to deliver a guide based on the acceptance criteria. 
- [ ] The volunteers must understand the value of a strong portfolio and the different ways work can be displayed (i.e. technically capable) 
- [ ] The volunteers should have worked with a CYF Cohort during Launch Project or Portfolio Module
- [ ] The volunteers should come from at least 2 regions

**Responsible**
@Barny-6

**Stakeholders**
@kfklein15

**Approvers**
@barny-6

**Comment by kfklein15** [comment]
Really good, @Barny-6 
I would be more specific in saying the minimum number of volunteers you need for this. 2? From the same region or from different regions? 

From a skills/experience perspective: must these volunteers have done some kind of hiring previously?

**Comment by Barny-6** [comment]
Criteria here - https://github.com/CodeYourFuture/Barny/issues/33

**Comment by Barny-6** [comment]
Hey @SallyMcGrath, This is a bit of work I was going to start today but if you decide that this is already being done as you said in the meeting then please close this issue. Thanks

**Comment by SallyMcGrath** [comment]
Hmm, what do I think. I think this is a lot of formal process, which we may or may not do but I don't think we need to block what I said in our call with this. What I suggested is we all as staff start posing the _question_: where is that work? How can I see that? Can you show me that? Instead of defining the solution. 

We don't want to limit trainee portfolios to our own imaginations/abilities by prescribing things in too limited a fashion. I understand you need a minimum criteria for job applications, and I'm not saying you cannot do this, I'm saying this looks like a large undertaking and I don't think it needs to be as we already have most of what we need. 

We already have a[ good developer portfolio guide](https://www.joshwcomeau.com/effective-portfolio/), free from Josh Comeau, and an accompanying talk on our Youtube.  It covers writing case studies. I also provided a simple answer months ago for devops - write some incident reports. It's not a big deal to write a case study or incident report. If you want a guide to point to, open a ticket on https://github.com/CodeYourFuture/curriculum and/or share your requirements on https://github.com/CodeYourFuture/curriculum/discussions/386 and let the Portfolio vols think about it.

Here's the example I gave back in November BTW

> ...They do, but you do them differently. DevOps is (meant to be) about documenting and surfacing operations to dev teams, so you write some case studies explaining your work. The ideal would be two [Incident ](https://sre.google/workbook/incident-response/)reports.
> 
> 
> Germán Bencci
>   3 months ago
> that's so interesting. Do you think we should expect them to write 2 incident reports as part of their applications?
> 
> 
> Sally McGrath
>   3 months ago
> Yeah it would be a good idea. It doesn't need to be a big thing. I just asked Claude to write an example:

> Here is a 295 word incident report by a junior DevOps engineer:
> Incident Report
> Date: Thursday, October 26, 2023
> Summary:
> At approximately 9:15 AM PST on Thursday, October 26th, our monitoring system alerted us to degraded application performance for our e-commerce website. After investigating, I determined the root cause was due to an unexpected spike in traffic that was overloading our web servers.
> Timeline:
> - 9:15 AM - Alert triggered by monitoring system due to high CPU usage on web servers
> - 9:16 AM - Checked logs and metrics, confirmed traffic spike to be source of performance degradation
> - 9:18 AM - Escalated to senior DevOps engineer per runbook procedure
> - 9:20 AM - Conferred with senior engineer on mitigation strategy
> - 9:25 AM - Added 2 additional web server nodes to load balancer pool per senior engineer direction
> - 9:35 AM - New web server nodes fully operational and receiving traffic
> - 9:45 AM - Confirmed resolution of incident, CPU loads back to normal thresholds
> Root Cause Analysis:
> The performance degradation was caused by an unexpected traffic spike driven by a seasonal promotion on the site. Additional server capacity was needed to handle the increased load.
> Lessons Learned:
> - Improved auto-scaling policies needed - additional nodes should have been spun up automatically
> - Traffic forecasting should take promotions and seasonal events into account
> - Runbook entry should be created for traffic spike scenarios
> By documenting this incident and identifying areas of improvement for our systems and procedures, we can continue to enhance the stability and resiliency of our e-commerce platform.
